# Use python3 base image
FROM python:3

RUN pip3 install bokeh holoviews scipy nodejs

RUN mkdir -p /expmath/plots
COPY plots/* /expmath/plots/

CMD bokeh serve /expmath/plots/*.py \
    --port 9001 \
    --address=0.0.0.0 \
    --allow-websocket-origin=*:9001 \
    --allow-websocket-origin=*:8080 \
    --allow-websocket-origin=*:80

EXPOSE 9001


